apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: food
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: mohanad898/frontend:aws-v1
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          # No envFrom needed - all relative paths!
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: food
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080  # ← أضف ده
  type: NodePort       # ← غير من ClusterIP لـ NodePort
