name: Deploy FoodApp to K3s

on:
  push: 
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      #  SSH deploy to EC2
      - name: Deploy to K3s via SSH
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            #  Install git & docker if not installed
            sudo apt update && sudo apt install -y git docker.io docker-compose
            
            #  Setup kubeconfig
            mkdir -p $HOME/.kube

            #  Clone repo (or pull latest if exists)
            if [ -d "$HOME/foodApp" ]; then
              cd $HOME/foodApp && git pull origin main
            else
              git clone https://github.com/${{ github.repository }} $HOME/foodApp
            fi

            cd $HOME/foodApp

            #  Docker login
            echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

            #  Build & push Docker images
            docker build -t ${{ secrets.DOCKER_USERNAME }}/frontend:latest ./Frontend
            docker push ${{ secrets.DOCKER_USERNAME }}/frontend:latest

            docker build -t ${{ secrets.DOCKER_USERNAME }}/backend:latest ./Backend
            docker push ${{ secrets.DOCKER_USERNAME }}/backend:latest

            docker build -t ${{ secrets.DOCKER_USERNAME }}/admin:latest ./Admin
            docker push ${{ secrets.DOCKER_USERNAME }}/admin:latest

            #  Deploy K3s manifests
            NAMESPACE=food
            kubectl get namespace $NAMESPACE || kubectl create namespace $NAMESPACE
            kubectl apply -f $HOME/foodApp/k8s/mongodb -n $NAMESPACE
            kubectl apply -f $HOME/foodApp/k8s/backend -n $NAMESPACE
            kubectl apply -f $HOME/foodApp/k8s/admin -n $NAMESPACE
            kubectl apply -f $HOME/foodApp/k8s/frontend -n $NAMESPACE
            kubectl apply -f $HOME/foodApp/k8s/food-secrets.yaml -n $NAMESPACE

