# .github/workflows/ci-cd.yaml
name: CI/CD FoodApp

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repo
      - name: Checkout Repository
        uses: actions/checkout@v3

      # 2️⃣ Login to Docker Hub
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 3️⃣ Build & Push backend image
      - name: Build & Push Backend Image
        run: |
          docker build -t mohanad898/backend:latest ./Backend
          docker push mohanad898/backend:latest

      # 4️⃣ Build & Push frontend image
      - name: Build & Push Frontend Image
        run: |
          docker build -t mohanad898/frontend:latest ./Frontend
          docker push mohanad898/frontend:latest

      # 5️⃣ Build & Push admin image
      - name: Build & Push Admin Image
        run: |
          docker build -t mohanad898/admin:latest ./Admin
          docker push mohanad898/admin:latest

      # 6️⃣ Setup kubeconfig
      - name: Setup Kubeconfig
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBE_CONFIG }}" > $HOME/.kube/config
          chmod 600 $HOME/.kube/config

      # 7️⃣ Deploy to k3s
      - name: Deploy to Kubernetes
        run: |
          # Create namespace if not exists
          kubectl get ns food || kubectl create ns food

          # Apply Secrets
          kubectl apply -f k8s/food-secrets.yaml -n food

          # Apply MongoDB (Private Node)
          kubectl apply -f k8s/mongodb/mongo-StatefulSet-Service.yaml -n food

          # Apply Backend (Public Node)
          kubectl apply -f k8s/backend/backend.yaml -n food

          # Apply Frontend (Public Node)
          kubectl apply -f k8s/frontend/frontend.yaml -n food

          # Apply Admin (Public Node)
          kubectl apply -f k8s/admin/admin.yaml -n food

      # 8️⃣ Rollout status check
      - name: Check Deployment Status
        run: |
          kubectl rollout status deployment/backend -n food
          kubectl rollout status deployment/frontend -n food
          kubectl rollout status deployment/admin -n food
          kubectl get pods -n food -o wide
